name: build-test

on:
  pull_request:
    types:
    - synchronize
    - opened
    - reopened
    - ready_for_review
  push:
    branches:
    - '!master'

jobs:
  # test npm scripts
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - run: |
        # set default git config for unit tests
        git config --global user.email "gha@ci"
        git config --global user.name "ci"
    - run: |
        npm install
        npm run all
  # test against master branch
  test-default-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
    - run: ls -hal .
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test against a base branch that's not master
  test-non-default-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        base_ref: add-base-ref-input-base-test
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test with custom file that returns a diff
  test-diff-detected:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config_file: __tests__/rules-match-all.yml
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'true' ] || exit 1
  # test with custom file that returns no diff
  test-no-diff-detected:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        config_file: __tests__/rules-no-diff-detected.yml
    - name: Ensure a change has been detected
      run: |
        [ "${DIFF_DETECTED}" == 'false' ] || exit 1
